[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
env_logger = "0.11.3"
koopa = "0.0.7"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
log = "0.4.21"
once_cell = "1.19.0"
