CompUnit  ::= FuncDef;

FuncDef   ::= FuncType IDENT "(" ")" Block;
FuncType  ::= "int";

Block     ::= "{" Stmt "}";
Stmt      ::= "return" Exp ";";
Exp       ::= UnaryExp;

UnaryExp  ::= PrimaryExp | UnaryOp UnaryExp;

PrimaryExp ::= "(" Exp ")" | Number;

UnaryOp ::= "+" | "-" | "!";

Number    ::= INT_CONST;
