CompUnit  ::= FuncDef;

FuncDef   ::= FuncType IDENT "(" ")" Block;
FuncType  ::= "int";

Block     ::= "{" Stmt "}";
Stmt      ::= "return" Exp ";";
Exp       ::= LOrExp;

LOrExp ::= LAndExp | LOrExp "||" LAndExp;

LAndExp ::= EqExp | LAndExp "&&" EqExp;

EqExp ::= RelExp | EqExp ("==" | "!=") RelExp;

RelExp ::= AddExp | RelExp ("<" | ">" | "<=" | ">=") AddExp;

MulExp ::= UnaryExp | MulExp ("*" | "/" | "%") MulExp;

AddExp ::= MulExp | AddExp ("+" | "-") MulExp;

UnaryExp  ::= PrimaryExp | UnaryOp UnaryExp;

PrimaryExp ::= "(" Exp ")" | Number;

UnaryOp ::= "+" | "-" | "!";

Number    ::= INT_CONST;
